### PR TITLE
Retrieve request from context instead of using middleware

### PR DESCRIPTION
**Pull request by ajhodges**
As per my comment in https://github.com/InterSIS/django-rest-serializer-field-permissions/issues/15#issuecomment-686538813

I believe the request can be retrieved from `self.context` in a Serializer (versus using a middleware, or `self._context`).

I added some failing tests using the example provided in #15 and the old `self._context` method, and then switched to `self.context`, and the tests pass.

### CODE REVIEW

**Comment by thatguysimon** [comment]
@ajhodges I think you can remove the `RuntimeError` that's raised if `request is None`. Or at least change the wording.

**Comment by JASchilz** [comment]
Hi all! I'll work to evaluate this this weekend.

**Review by JASchilz — APPROVED** [review]
This all looks reasonable! I'm going to merge and release a release candidate.

**Comment by JASchilz** [comment]
Hi @thatguysimon @ajhodges given the (very small, but still present) API changes identified by @thatguysimon I'm upping the major version number on this release.

I've uploaded this to pypi as 4.0.0rc1. Could you both take a look and let me know if this addresses the issues you've raised? If so, I'll make an official release.

Thanks for your help on this! As I've mentioned elsewhere in the project I haven't used these libraries myself in a few years. It's hard for me to evaluate new features, but I'll definitely try to move with respect to bugs.

I do also appreciate the proposed feature work from @ajhodges , and I'm going to put some thought to how I can at least identify those as in-scope or out-of-scope for this project, and take some kind of action on them. No promise there, but definitely an inclination.

**Comment by thatguysimon** [comment]
@JASchilz Looks good on my end. Thanks for the quick response!
One minor thing is like I said above, the error message [here](https://github.com/ajhodges/django-rest-serializer-field-permissions/blob/f61e41a36c989421044f8d79efa6ebfe8b455011/rest_framework_serializer_field_permissions/serializers.py#L29) is no longer relevant.

**Pull request merged**
